name: Bug Report
description: Create a bug report to help us improve.
title: "[BUG]: "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Please search for this issue in the issues page first. Avoid duplication.
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Output of `tidal-dl --version`.
      placeholder: |
        e.g. 3.0.0
    validations:
      required: true
  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: Describe the platform on which the tool has been used.
      placeholder: |
        Windows\Linux\Macos\Android
    validations:
      required: true
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: Describe the bug as accurately as possible.
      placeholder: |
        How to reappear this bug? 
        Which albumID\trackID\artistID?
        Please describe in detail.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Please add screenshots if available.
    validations:
      required: false
