name: Feature Request
description: Open a feature request to Tidal-Media-Downloader.
title: "[FEATURE]: "
labels: feature request
body:
  - type: markdown
    attributes:
      value: |
        Please search for this issue in the issues page first. Avoid duplication.
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: Describe the feature as accurately as possible.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Please add screenshots if available.
    validations:
      required: false
